import { execFileSync, spawnSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import sharp from 'sharp';
import { ebookCatalog, ebookPilotPosts } from './ebooks.config.mjs';
import {
  buildCoverSvg,
  buildOpds,
  normalizeDate,
  slugFromPostFile
} from './ebook-lib.mjs';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const postsDirectory = join(projectRoot, 'src/content/posts');
const publicDirectory = join(projectRoot, 'public');
const targetDirectory = join(publicDirectory, 'ebooks');
const markerName = '.generated-by-build-ebooks';
const opdsPath = join(publicDirectory, 'opds.xml');
const filterPath = join(projectRoot, 'scripts/pandoc-math-svg.mjs');
const cssPath = join(projectRoot, 'scripts/ebook.css');
const buildAll = process.argv.includes('--all');

function assertCommand(command, args = ['--version']) {
  try {
    execFileSync(command, args, { stdio: 'ignore' });
  } catch {
    throw new Error(`${command} is required to build EPUB files`);
  }
}

function readPost(file) {
  const path = join(postsDirectory, file);
  const raw = readFileSync(path, 'utf8');
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/u);
  if (!match) throw new Error(`${file}: missing YAML frontmatter`);
  const data = yaml.load(match[1]) ?? {};
  if (!data.title || !data.description || !data.date) {
    throw new Error(`${file}: title, description, and date are required for EPUB`);
  }
  return { path, raw, data };
}

function getPostSpecs() {
  if (!buildAll) return ebookPilotPosts;
  return readdirSync(postsDirectory)
    .filter((file) => file.endsWith('.md'))
    .map((file) => ({ file, expects: {} }))
    .filter(({ file }) => !readPost(file).data.draft);
}

function runPandoc(args, environment) {
  const result = spawnSync('pandoc', args, {
    cwd: projectRoot,
    env: { ...process.env, ...environment },
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024
  });
  if (result.status !== 0) {
    throw new Error(`Pandoc failed:\n${result.stdout}\n${result.stderr}`);
  }
  if (result.stderr.trim()) process.stderr.write(result.stderr);
}

function ensureGeneratedOutputIsReplaceable() {
  if (existsSync(targetDirectory) && !existsSync(join(targetDirectory, markerName))) {
    throw new Error(`${targetDirectory} exists without the generator ownership marker`);
  }
  if (existsSync(opdsPath)) {
    const existing = readFileSync(opdsPath, 'utf8');
    if (!existing.includes('Generated by scripts/build-ebooks.mjs')) {
      throw new Error(`${opdsPath} exists but was not generated by this script`);
    }
  }
}

assertCommand('pandoc');
ensureGeneratedOutputIsReplaceable();

const stagingDirectory = join(publicDirectory, `.ebooks-staging-${process.pid}`);
const workDirectory = mkdtempSync(join(tmpdir(), 'keepkeen-ebooks-'));
mkdirSync(stagingDirectory);

try {
  const manifest = [];
  const feedEntries = [];

  for (const spec of getPostSpecs()) {
    const { file, expects = {} } = spec;
    const { path: sourcePath, raw, data } = readPost(file);
    const slug = slugFromPostFile(file);
    const outputStem = spec.filenameStem ?? slug;
    const articleWorkDirectory = join(workDirectory, slug);
    const mathDirectory = join(articleWorkDirectory, 'math');
    const statsPath = join(articleWorkDirectory, 'math-stats.json');
    const metadataPath = join(articleWorkDirectory, 'metadata.yaml');
    const coverWorkPath = join(articleWorkDirectory, 'cover.png');
    const coverFilename = `${outputStem}.png`;
    const epubFilename = `${outputStem}.epub`;
    const epubPath = join(stagingDirectory, epubFilename);
    mkdirSync(mathDirectory, { recursive: true });

    const published = normalizeDate(data.date);
    const updated = normalizeDate(data.updatedDate ?? data.date);
    const articleUrl = new URL(`/blog/${slug}/`, ebookCatalog.siteUrl).toString();
    const identifier = articleUrl;
    const metadata = {
      title: String(data.title),
      author: ebookCatalog.author,
      date: published.slice(0, 10),
      lang: data.lang ?? ebookCatalog.language,
      identifier,
      description: String(data.description),
      rights: 'Copyright © Liuliming. All rights reserved.'
    };
    writeFileSync(metadataPath, yaml.dump(metadata, { lineWidth: -1 }));

    const coverSvg = buildCoverSvg({
      title: data.title,
      description: data.description,
      date: published,
      author: ebookCatalog.author
    });
    await sharp(Buffer.from(coverSvg)).png({ compressionLevel: 9 }).toFile(coverWorkPath);
    await sharp(coverWorkPath).toFile(join(stagingDirectory, coverFilename));

    runPandoc(
      [
        '--from=markdown+yaml_metadata_block+tex_math_dollars+raw_html',
        '--to=epub3',
        '--standalone',
        '--file-scope',
        '--toc',
        '--toc-depth=3',
        '--split-level=2',
        `--metadata-file=${metadataPath}`,
        `--css=${cssPath}`,
        `--epub-cover-image=${coverWorkPath}`,
        `--resource-path=${postsDirectory}`,
        `--filter=${filterPath}`,
        '--wrap=none',
        '--output',
        epubPath,
        sourcePath
      ],
      {
        EBOOK_MATH_DIR: mathDirectory,
        EBOOK_MATH_STATS: statsPath,
        EBOOK_RESOURCE_DIR: postsDirectory,
        EBOOK_SITE_URL: ebookCatalog.siteUrl,
        EBOOK_ARTICLE_URL: articleUrl,
        EBOOK_INLINE_MATH_SCALE: String(ebookCatalog.mathScale.inline),
        EBOOK_DISPLAY_MATH_SCALE: String(ebookCatalog.mathScale.display)
      }
    );

    const mathStats = JSON.parse(readFileSync(statsPath, 'utf8'));
    const sourceImageCount = (raw.match(/!\[[^\]]*\]\([^)]+\)/gu) ?? []).length;
    const codeFenceCount = (raw.match(/^```/gmu) ?? []).length;
    if (expects.math && mathStats.formulaCount === 0) {
      throw new Error(`${file}: pilot expected formulas but the filter found none`);
    }
    if (expects.images && sourceImageCount === 0) {
      throw new Error(`${file}: pilot expected images but the source has none`);
    }
    if (expects.code && codeFenceCount === 0) {
      throw new Error(`${file}: pilot expected code blocks but the source has none`);
    }

    const epubUrl = new URL(`/ebooks/${epubFilename}`, ebookCatalog.siteUrl).toString();
    const coverUrl = new URL(`/ebooks/${coverFilename}`, ebookCatalog.siteUrl).toString();
    const bytes = statSync(epubPath).size;
    const record = {
      file,
      slug,
      title: String(data.title),
      description: String(data.description),
      published,
      updated,
      articleUrl,
      epubFilename,
      epubUrl,
      coverFilename,
      coverUrl,
      bytes,
      sourceImageCount,
      codeFenceCount,
      ...mathStats
    };
    manifest.push(record);
    feedEntries.push({ id: identifier, ...record });
    console.log(
      `Built ${epubFilename} (${Math.round(bytes / 1024)} KiB, ${mathStats.formulaCount} formulas)`
    );
  }

  feedEntries.sort((a, b) => b.updated.localeCompare(a.updated));
  writeFileSync(join(stagingDirectory, 'catalog.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(join(stagingDirectory, markerName), 'Generated by scripts/build-ebooks.mjs\n');
  const opds = buildOpds(feedEntries, ebookCatalog);
  const opdsStagingPath = join(publicDirectory, `.opds-${process.pid}.xml`);
  writeFileSync(opdsStagingPath, opds);

  if (existsSync(targetDirectory)) rmSync(targetDirectory, { recursive: true });
  renameSync(stagingDirectory, targetDirectory);
  if (existsSync(opdsPath)) rmSync(opdsPath);
  renameSync(opdsStagingPath, opdsPath);
  console.log(`Generated ${manifest.length} EPUB files and ${ebookCatalog.feedPath}`);
} finally {
  if (existsSync(stagingDirectory)) rmSync(stagingDirectory, { recursive: true });
  rmSync(workDirectory, { recursive: true, force: true });
}
