import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import JSZip from 'jszip';
import sharp from 'sharp';
import { ebookCatalog, ebookSeries } from './ebooks.config.mjs';
import {
  buildCoverSvg,
  buildOpds,
  buildOpdsNavigation,
  buildSeriesFilename,
  normalizeDate,
  slugFromPostFile
} from './ebook-lib.mjs';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const postsDirectory = join(projectRoot, 'src/content/posts');
const publicDirectory = join(projectRoot, 'public');
const targetDirectory = join(publicDirectory, 'ebooks');
const markerName = '.generated-by-build-ebooks';
const opdsPath = join(publicDirectory, 'opds.xml');
const seriesFeedDirectory = join(publicDirectory, 'opds');
const filterPath = join(projectRoot, 'scripts/pandoc-math-svg.mjs');
const cssPath = join(projectRoot, 'scripts/ebook.css');
const seriesBySlug = new Map(ebookSeries.map((series) => [series.slug, series]));

function assertCommand(command, args = ['--version']) {
  try {
    execFileSync(command, args, { stdio: 'ignore' });
  } catch {
    throw new Error(`${command} is required to build EPUB files`);
  }
}

function readPost(file) {
  const path = join(postsDirectory, file);
  const raw = readFileSync(path, 'utf8');
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/u);
  if (!match) throw new Error(`${file}: missing YAML frontmatter`);
  const data = yaml.load(match[1]) ?? {};
  if (!data.title || !data.description || !data.date) {
    throw new Error(`${file}: title, description, and date are required for EPUB`);
  }
  return { path, raw, data };
}

function getPostSpecs() {
  return readdirSync(postsDirectory)
    .filter((file) => file.endsWith('.md'))
    .sort()
    .map((file) => ({ file }))
    .filter(({ file }) => !readPost(file).data.draft);
}

function getSeries(data, file) {
  const seriesSlug = data.series ?? 'other';
  const series = seriesBySlug.get(seriesSlug);
  if (!series) throw new Error(`${file}: unknown ebook series ${seriesSlug}`);
  const seriesOrder = data.seriesOrder ?? 1;
  if (!Number.isInteger(seriesOrder) || seriesOrder < 1) {
    throw new Error(`${file}: seriesOrder must be a positive integer`);
  }
  return { ...series, order: seriesOrder };
}

function runPandoc(args, environment) {
  const result = spawnSync('pandoc', args, {
    cwd: projectRoot,
    env: { ...process.env, ...environment },
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024
  });
  if (result.status !== 0) {
    throw new Error(`Pandoc failed:\n${result.stdout}\n${result.stderr}`);
  }
  if (/Could not convert TeX math/u.test(result.stderr)) {
    throw new Error(`Pandoc left unconverted TeX math:\n${result.stderr}`);
  }
  if (result.stderr.trim()) process.stderr.write(result.stderr);
}

function ensureGeneratedOutputIsReplaceable() {
  if (existsSync(targetDirectory) && !existsSync(join(targetDirectory, markerName))) {
    throw new Error(`${targetDirectory} exists without the generator ownership marker`);
  }
  if (existsSync(opdsPath)) {
    const existing = readFileSync(opdsPath, 'utf8');
    if (!existing.includes('Generated by scripts/build-ebooks.mjs')) {
      throw new Error(`${opdsPath} exists but was not generated by this script`);
    }
  }
  if (
    existsSync(seriesFeedDirectory) &&
    !existsSync(join(seriesFeedDirectory, markerName))
  ) {
    throw new Error(`${seriesFeedDirectory} exists without the generator ownership marker`);
  }
}

assertCommand('pandoc');
ensureGeneratedOutputIsReplaceable();

const stagingDirectory = join(publicDirectory, `.ebooks-staging-${process.pid}`);
const feedStagingDirectory = join(publicDirectory, `.opds-staging-${process.pid}`);
const opdsStagingPath = join(publicDirectory, `.opds-${process.pid}.xml`);
const workDirectory = mkdtempSync(join(tmpdir(), 'keepkeen-ebooks-'));
mkdirSync(stagingDirectory);
mkdirSync(feedStagingDirectory);

try {
  const manifest = [];
  const feedEntriesBySeries = new Map(ebookSeries.map((series) => [series.slug, []]));
  const seenSeriesOrders = new Set();

  for (const spec of getPostSpecs()) {
    const { file } = spec;
    const { path: sourcePath, raw, data } = readPost(file);
    const slug = slugFromPostFile(file);
    const series = getSeries(data, file);
    const seriesOrderKey = `${series.slug}\0${series.order}`;
    if (seenSeriesOrders.has(seriesOrderKey)) {
      throw new Error(`${file}: duplicate ${series.slug} seriesOrder ${series.order}`);
    }
    seenSeriesOrders.add(seriesOrderKey);
    const outputStem = buildSeriesFilename(data.title, series.order);
    const articleWorkDirectory = join(workDirectory, slug);
    const mathDirectory = join(articleWorkDirectory, 'math');
    const statsPath = join(articleWorkDirectory, 'math-stats.json');
    const metadataPath = join(articleWorkDirectory, 'metadata.yaml');
    const coverWorkPath = join(articleWorkDirectory, 'cover.png');
    const coverFilename = `${outputStem}.png`;
    const epubFilename = `${outputStem}.epub`;
    const seriesOutputDirectory = join(stagingDirectory, series.directory);
    const epubRelativePath = `${series.directory}/${epubFilename}`;
    const coverRelativePath = `${series.directory}/${coverFilename}`;
    const epubPath = join(seriesOutputDirectory, epubFilename);
    const coverPath = join(seriesOutputDirectory, coverFilename);
    mkdirSync(mathDirectory, { recursive: true });
    mkdirSync(seriesOutputDirectory, { recursive: true });

    const published = normalizeDate(data.date);
    const updated = normalizeDate(data.updatedDate ?? data.date);
    const articleUrl = new URL(`/blog/${slug}/`, ebookCatalog.siteUrl).toString();
    const identifier = articleUrl;
    // Pandoc's built-in translation table supports the BCP 47 script tag
    // `zh-Hans`, while `zh-CN` emits two warnings for every generated book.
    const ebookLanguage = (data.lang ?? ebookCatalog.language) === 'zh-CN'
      ? 'zh-Hans'
      : (data.lang ?? ebookCatalog.language);
    const metadata = {
      title: String(data.title),
      author: ebookCatalog.author,
      date: published.slice(0, 10),
      lang: ebookLanguage,
      identifier,
      description: String(data.description),
      subject: series.title,
      'belongs-to-collection': series.title,
      'group-position': series.order,
      rights: 'Copyright © Liuliming. All rights reserved.'
    };
    writeFileSync(metadataPath, yaml.dump(metadata, { lineWidth: -1 }));

    const coverSvg = buildCoverSvg({
      title: data.title,
      description: data.description,
      date: published,
      author: ebookCatalog.author
    });
    await sharp(Buffer.from(coverSvg)).png({ compressionLevel: 9 }).toFile(coverWorkPath);
    await sharp(coverWorkPath).toFile(coverPath);

    runPandoc(
      [
        '--from=markdown+yaml_metadata_block+tex_math_dollars+raw_html',
        '--to=epub3',
        ...(ebookCatalog.mathRenderer === 'mathml' ? ['--math-method=mathml'] : []),
        '--standalone',
        '--file-scope',
        '--toc',
        '--toc-depth=3',
        '--split-level=2',
        `--metadata-file=${metadataPath}`,
        `--metadata=lang:${ebookLanguage}`,
        `--css=${cssPath}`,
        `--epub-cover-image=${coverWorkPath}`,
        `--resource-path=${postsDirectory}`,
        `--filter=${filterPath}`,
        '--wrap=none',
        '--output',
        epubPath,
        sourcePath
      ],
      {
        SOURCE_DATE_EPOCH: String(Math.floor(new Date(updated).getTime() / 1000)),
        EBOOK_MATH_DIR: mathDirectory,
        EBOOK_MATH_STATS: statsPath,
        EBOOK_RESOURCE_DIR: postsDirectory,
        EBOOK_PUBLIC_DIR: publicDirectory,
        EBOOK_SITE_URL: ebookCatalog.siteUrl,
        EBOOK_ARTICLE_URL: articleUrl,
        EBOOK_MATH_RENDERER: ebookCatalog.mathRenderer,
        EBOOK_INLINE_MATH_SCALE: String(ebookCatalog.mathScale.inline),
        EBOOK_DISPLAY_MATH_SCALE: String(ebookCatalog.mathScale.display)
      }
    );

    const mathStats = JSON.parse(readFileSync(statsPath, 'utf8'));
    const sourceImageCount = (raw.match(/!\[[^\]]*\]\([^)]+\)/gu) ?? []).length;
    const codeFenceCount = (raw.match(/^```/gmu) ?? []).length;
    const bytes = statSync(epubPath).size;
    const sha256 = createHash('sha256').update(readFileSync(epubPath)).digest('hex');
    const coverSha256 = createHash('sha256').update(readFileSync(coverPath)).digest('hex');
    const epubUrl = new URL(`/ebooks/${epubRelativePath}`, ebookCatalog.siteUrl);
    epubUrl.searchParams.set('v', sha256.slice(0, 16));
    const coverUrl = new URL(`/ebooks/${coverRelativePath}`, ebookCatalog.siteUrl);
    coverUrl.searchParams.set('v', coverSha256.slice(0, 16));
    const record = {
      file,
      slug,
      title: String(data.title),
      description: String(data.description),
      seriesSlug: series.slug,
      seriesTitle: series.title,
      seriesDirectory: series.directory,
      seriesOrder: series.order,
      published,
      updated,
      articleUrl,
      epubFilename,
      epubRelativePath,
      epubUrl: epubUrl.toString(),
      coverFilename,
      coverRelativePath,
      coverUrl: coverUrl.toString(),
      bytes,
      sha256,
      coverSha256,
      sourceImageCount,
      codeFenceCount,
      ...mathStats
    };
    manifest.push(record);
    feedEntriesBySeries.get(series.slug).push({ id: identifier, ...record, title: outputStem });
    console.log(
      `Built ${epubRelativePath} (${Math.round(bytes / 1024)} KiB, ${mathStats.formulaCount} formulas)`
    );
  }

  const seriesIndexes = new Map(ebookSeries.map((series, index) => [series.slug, index]));
  manifest.sort(
    (a, b) =>
      seriesIndexes.get(a.seriesSlug) - seriesIndexes.get(b.seriesSlug) ||
      a.seriesOrder - b.seriesOrder
  );
  writeFileSync(join(stagingDirectory, 'catalog.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  const syncBooks = manifest.map((record) => ({
    slug: record.slug,
    title: record.title,
    seriesSlug: record.seriesSlug,
    seriesTitle: record.seriesTitle,
    seriesOrder: record.seriesOrder,
    relativePath: record.epubRelativePath,
    url: record.epubUrl,
    bytes: record.bytes,
    sha256: record.sha256,
    updated: record.updated
  }));
  const revision = createHash('sha256').update(JSON.stringify(syncBooks)).digest('hex');
  const generatedAt = manifest.map((record) => record.updated).sort().at(-1);
  const bundleFilename = 'KeepKeen-Blog-library.zip';
  const bundlePath = join(stagingDirectory, bundleFilename);
  const bundle = new JSZip();
  const bundleEntryDate = new Date(2000, 0, 1);
  for (const record of manifest) {
    bundle.file(
      record.epubRelativePath,
      readFileSync(join(stagingDirectory, record.epubRelativePath)),
      { date: bundleEntryDate, createFolders: false }
    );
  }
  const bundleBuffer = await bundle.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
    platform: 'UNIX'
  });
  writeFileSync(bundlePath, bundleBuffer);
  const bundleSha256 = createHash('sha256').update(bundleBuffer).digest('hex');
  const bundleUrl = new URL(`/ebooks/${bundleFilename}`, ebookCatalog.siteUrl);
  bundleUrl.searchParams.set('v', bundleSha256.slice(0, 16));
  writeFileSync(
    join(stagingDirectory, 'library.json'),
    `${JSON.stringify({
      schemaVersion: 1,
      revision,
      generatedAt,
      rootDirectory: ebookCatalog.libraryDirectory,
      bookCount: syncBooks.length,
      bundle: {
        url: bundleUrl.toString(),
        bytes: bundleBuffer.length,
        sha256: bundleSha256
      },
      books: syncBooks
    }, null, 2)}\n`
  );
  writeFileSync(join(stagingDirectory, markerName), 'Generated by scripts/build-ebooks.mjs\n');

  const sections = [];
  for (const series of ebookSeries) {
    const entries = feedEntriesBySeries.get(series.slug);
    if (entries.length === 0) continue;
    entries.sort((a, b) => a.seriesOrder - b.seriesOrder);
    const feedPath = `${ebookCatalog.seriesFeedDirectory}/${series.slug}.xml`;
    const feedUrl = new URL(feedPath, ebookCatalog.siteUrl).toString();
    const updated = entries.map((entry) => entry.updated).sort().at(-1);
    writeFileSync(
      join(feedStagingDirectory, `${series.slug}.xml`),
      buildOpds(entries, {
        ...ebookCatalog,
        title: `${ebookCatalog.title} · ${series.title}`,
        description: `${series.title}系列，共 ${entries.length} 本。`,
        feedPath,
        startPath: ebookCatalog.feedPath
      })
    );
    sections.push({
      title: `${series.directory}（${entries.length} 本）`,
      description: `${series.title}系列`,
      count: entries.length,
      updated,
      feedUrl
    });
  }
  writeFileSync(join(feedStagingDirectory, markerName), 'Generated by scripts/build-ebooks.mjs\n');
  writeFileSync(opdsStagingPath, buildOpdsNavigation(sections, ebookCatalog));

  if (existsSync(targetDirectory)) rmSync(targetDirectory, { recursive: true });
  renameSync(stagingDirectory, targetDirectory);
  if (existsSync(seriesFeedDirectory)) rmSync(seriesFeedDirectory, { recursive: true });
  renameSync(feedStagingDirectory, seriesFeedDirectory);
  if (existsSync(opdsPath)) rmSync(opdsPath);
  renameSync(opdsStagingPath, opdsPath);
  console.log(
    `Generated ${manifest.length} EPUB files, ${sections.length} series feeds, and ${ebookCatalog.syncManifestPath}`
  );
} finally {
  if (existsSync(stagingDirectory)) rmSync(stagingDirectory, { recursive: true });
  if (existsSync(feedStagingDirectory)) rmSync(feedStagingDirectory, { recursive: true });
  if (existsSync(opdsStagingPath)) rmSync(opdsStagingPath);
  rmSync(workDirectory, { recursive: true, force: true });
}
